version: '3' # require
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # docker 內部 80 指向 localhost 的80
      - "443:443"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      # - "/etc/letsencrypt:/etc/letsencrypt"
    depends_on:
      - web
    links:
      - web:app
  web:
    build: ./
    ports:
      - "1337:1337"